from __future__ import annotations

import argparse
import ast
import difflib
from dataclasses import dataclass
from pathlib import Path


DEFAULT_DOC_PATH = Path("logs/generated/architecture_metrics.md")
PRODUCTION_ROOT = Path("harness")
TEST_ROOT = Path("tests")


@dataclass(frozen=True)
class FileMetric:
    path: str
    loc: int


@dataclass(frozen=True)
class FunctionMetric:
    path: str
    name: str
    lineno: int
    loc: int


@dataclass(frozen=True)
class ArchitectureMetrics:
    production_files: tuple[FileMetric, ...]
    test_files: tuple[FileMetric, ...]
    functions: tuple[FunctionMetric, ...]

    @property
    def production_total_loc(self) -> int:
        return sum(item.loc for item in self.production_files)

    @property
    def test_total_loc(self) -> int:
        return sum(item.loc for item in self.test_files)

    @property
    def max_production_file(self) -> FileMetric:
        return max(self.production_files, key=lambda item: item.loc)

    @property
    def max_test_file(self) -> FileMetric:
        return max(self.test_files, key=lambda item: item.loc)

    @property
    def max_function(self) -> FunctionMetric:
        return max(self.functions, key=lambda item: item.loc)


@dataclass(frozen=True)
class ArchitectureThresholds:
    max_production_file_loc: int = 1_200
    max_test_file_loc: int = 3_500
    max_function_loc: int = 300
    max_production_total_loc: int = 18_000
    max_test_total_loc: int = 10_500


DEFAULT_THRESHOLDS = ArchitectureThresholds()


def collect_architecture_metrics(root: Path = Path(".")) -> ArchitectureMetrics:
    production_files = tuple(_file_metric(path, root) for path in _python_files(root / PRODUCTION_ROOT))
    test_files = tuple(_file_metric(path, root) for path in _python_files(root / TEST_ROOT))
    functions = tuple(_collect_functions(path, root) for path in _python_files(root / PRODUCTION_ROOT))
    return ArchitectureMetrics(
        production_files=tuple(sorted(production_files, key=lambda item: item.path)),
        test_files=tuple(sorted(test_files, key=lambda item: item.path)),
        functions=tuple(sorted((item for group in functions for item in group), key=lambda item: (item.path, item.lineno))),
    )


def render_architecture_metrics(metrics: ArchitectureMetrics | None = None) -> str:
    metrics = metrics or collect_architecture_metrics()
    thresholds = DEFAULT_THRESHOLDS
    lines = [
        "# Generated Architecture Metrics",
        "",
        "<!-- generated by `python -m harness.architecture.metrics --write`; do not edit by hand -->",
        "",
        "These metrics are intentionally coarse. They give maintainers a stable baseline for file size, test size, and function length without blocking normal development on minor movement.",
        "",
        "## Summary",
        "",
        "| Metric | Value | Guardrail |",
        "| --- | ---: | ---: |",
        f"| Production Python files | {len(metrics.production_files)} | - |",
        f"| Production total LOC | {metrics.production_total_loc} | {thresholds.max_production_total_loc} |",
        f"| Test Python files | {len(metrics.test_files)} | - |",
        f"| Test total LOC | {metrics.test_total_loc} | {thresholds.max_test_total_loc} |",
        f"| Largest production file | {metrics.max_production_file.path} ({metrics.max_production_file.loc}) | {thresholds.max_production_file_loc} |",
        f"| Largest test file | {metrics.max_test_file.path} ({metrics.max_test_file.loc}) | {thresholds.max_test_file_loc} |",
        f"| Longest function | {metrics.max_function.path}:{metrics.max_function.lineno} `{metrics.max_function.name}` ({metrics.max_function.loc}) | {thresholds.max_function_loc} |",
        "",
        "## Largest Production Files",
        "",
        "| LOC | Path |",
        "| ---: | --- |",
    ]
    lines.extend(f"| {item.loc} | `{item.path}` |" for item in _top(metrics.production_files, 12))
    lines.extend(
        [
            "",
            "## Largest Test Files",
            "",
            "| LOC | Path |",
            "| ---: | --- |",
        ]
    )
    lines.extend(f"| {item.loc} | `{item.path}` |" for item in _top(metrics.test_files, 12))
    lines.extend(
        [
            "",
            "## Longest Production Functions",
            "",
            "| LOC | Function |",
            "| ---: | --- |",
        ]
    )
    lines.extend(f"| {item.loc} | `{item.path}:{item.lineno}` `{item.name}` |" for item in _top(metrics.functions, 15))
    lines.append("")
    return "\n".join(lines)


def threshold_warnings(
    metrics: ArchitectureMetrics | None = None,
    thresholds: ArchitectureThresholds = DEFAULT_THRESHOLDS,
) -> list[str]:
    metrics = metrics or collect_architecture_metrics()
    warnings: list[str] = []
    if metrics.max_production_file.loc > thresholds.max_production_file_loc:
        warnings.append(
            f"largest production file {metrics.max_production_file.path} has {metrics.max_production_file.loc} LOC "
            f"(limit {thresholds.max_production_file_loc})"
        )
    if metrics.max_test_file.loc > thresholds.max_test_file_loc:
        warnings.append(
            f"largest test file {metrics.max_test_file.path} has {metrics.max_test_file.loc} LOC "
            f"(limit {thresholds.max_test_file_loc})"
        )
    if metrics.max_function.loc > thresholds.max_function_loc:
        warnings.append(
            f"longest function {metrics.max_function.path}:{metrics.max_function.lineno} has {metrics.max_function.loc} LOC "
            f"(limit {thresholds.max_function_loc})"
        )
    if metrics.production_total_loc > thresholds.max_production_total_loc:
        warnings.append(
            f"production total has {metrics.production_total_loc} LOC "
            f"(limit {thresholds.max_production_total_loc})"
        )
    if metrics.test_total_loc > thresholds.max_test_total_loc:
        warnings.append(f"test total has {metrics.test_total_loc} LOC (limit {thresholds.max_test_total_loc})")
    return warnings


def write_architecture_metrics(path: Path = DEFAULT_DOC_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_architecture_metrics(), encoding="utf-8")


def check_architecture_metrics(path: Path = DEFAULT_DOC_PATH) -> bool:
    expected = render_architecture_metrics()
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current != expected:
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff))
        return False
    for warning in threshold_warnings():
        print(f"[WARN] {warning}")
    return True


def _python_files(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(path for path in root.rglob("*.py") if "__pycache__" not in path.parts)


def _file_metric(path: Path, root: Path) -> FileMetric:
    return FileMetric(path=_relative(path, root), loc=len(path.read_text(encoding="utf-8").splitlines()))


def _collect_functions(path: Path, root: Path) -> tuple[FunctionMetric, ...]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    visitor = _FunctionLengthVisitor(_relative(path, root))
    visitor.visit(tree)
    return tuple(visitor.functions)


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _top(items: tuple[FileMetric, ...] | tuple[FunctionMetric, ...], count: int):
    return sorted(items, key=lambda item: item.loc, reverse=True)[:count]


class _FunctionLengthVisitor(ast.NodeVisitor):
    def __init__(self, path: str):
        self.path = path
        self.stack: list[str] = []
        self.functions: list[FunctionMetric] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        self.stack.append(node.name)
        self.generic_visit(node)
        self.stack.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._record_function(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._record_function(node)

    def _record_function(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
        name = ".".join([*self.stack, node.name])
        end_lineno = getattr(node, "end_lineno", node.lineno)
        self.functions.append(FunctionMetric(self.path, name, node.lineno, end_lineno - node.lineno + 1))
        self.stack.append(node.name)
        self.generic_visit(node)
        self.stack.pop()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check coarse architecture size metrics.")
    parser.add_argument("--write", action="store_true", help="write the generated metrics document")
    parser.add_argument("--check", action="store_true", help="fail if the generated metrics document is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_DOC_PATH, help="metrics output path")
    args = parser.parse_args(argv)

    if args.write:
        write_architecture_metrics(args.output)
    if args.check:
        return 0 if check_architecture_metrics(args.output) else 1
    if not args.write:
        print(render_architecture_metrics(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
