from __future__ import annotations

import argparse
import difflib
from pathlib import Path

from harness.artifacts.schemas import ROLE_PHASE_CONTRACTS, ArtifactVisibilityRule, RolePhaseContract
from harness.contracts.role_contracts import artifact_input_budget_for


DEFAULT_DOC_PATH = Path("docs/generated_visibility_matrix.md")


def render_visibility_matrix() -> str:
    lines = [
        "# Generated Role/Phase Visibility Matrix",
        "",
        "<!-- generated by `python -m harness.contracts.visibility_matrix --write`; do not edit by hand -->",
        "",
        "This document is generated from `RolePhaseContract`, role/phase input budgets, and artifact visibility rules.",
        "",
        "| Target role | Target phase | Required outputs | Input budget | Source role | Source phases | Artifact types | Round policy | Self policy | Condition |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for contract in _ordered_contracts():
        budget = artifact_input_budget_for(contract.role, contract.phase)
        budget_text = (
            f"max_files={budget.max_files}, max_file_bytes={budget.max_file_bytes}, "
            f"max_total_bytes={budget.max_total_bytes}, large_artifact_mode={budget.large_artifact_mode}"
        )
        required_outputs = ", ".join(f"`{name}`" for name in contract.required_outputs_with_delivery())
        rules = contract.visibility_rules or (None,)
        for rule in rules:
            lines.append(
                "| "
                + " | ".join(
                    _cell(value)
                    for value in (
                        contract.role,
                        contract.phase,
                        required_outputs,
                        budget_text,
                        rule.source_role if rule else "(none)",
                        _source_phases(rule),
                        _artifact_types(rule),
                        rule.round_policy if rule else "(none)",
                        rule.self_policy if rule else "(none)",
                        rule.condition if rule else "(none)",
                    )
                )
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


def write_visibility_matrix(path: Path = DEFAULT_DOC_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_visibility_matrix(), encoding="utf-8")


def check_visibility_matrix(path: Path = DEFAULT_DOC_PATH) -> bool:
    expected = render_visibility_matrix()
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return True
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(path),
        tofile="generated",
        lineterm="",
    )
    print("\n".join(diff))
    return False


def _ordered_contracts() -> list[RolePhaseContract]:
    return list(ROLE_PHASE_CONTRACTS.values())


def _source_phases(rule: ArtifactVisibilityRule | None) -> str:
    if rule is None:
        return "(none)"
    if rule.source_phases is None:
        return "(any)"
    return ", ".join(sorted(rule.source_phases))


def _artifact_types(rule: ArtifactVisibilityRule | None) -> str:
    if rule is None:
        return "(none)"
    return ", ".join(f"`{name}`" for name in sorted(rule.artifact_types))


def _cell(value: str) -> str:
    return value.replace("|", "\\|")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check the role/phase artifact visibility matrix.")
    parser.add_argument("--write", action="store_true", help="write the generated matrix to docs/generated_visibility_matrix.md")
    parser.add_argument("--check", action="store_true", help="fail if docs/generated_visibility_matrix.md is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_DOC_PATH, help="matrix output path")
    args = parser.parse_args(argv)

    if args.write:
        write_visibility_matrix(args.output)
    if args.check:
        return 0 if check_visibility_matrix(args.output) else 1
    if not args.write:
        print(render_visibility_matrix(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
